[versions]
kotlin = "1.5.31"
compose = "1.0.5"
koin = "3.1.4"
retrofit = "2.9.0"
gradleDependencyUpdate = "0.42.0"

[plugins]
gradleDependencyUpdate = { id = "com.github.ben-manes.versions", version.ref="gradleDependencyUpdate" }

[libraries]
android-pluginGradle = "com.android.tools.build:gradle:7.1.1"

androidx-activity-activityCompose = "androidx.activity:activity-compose:1.4.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.4.1"
androidx-preference = "androidx.preference:preference-ktx:1.1.1"
androidx-security-crypto = "androidx.security:security-crypto-ktx:1.1.0-alpha03"

androidx-compose-materialIconsExt = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }

junit = "junit:junit:4.13.2"

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidxCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

kotlin-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.0"
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

retrofit-converterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }