package org.alberto97.hisenseair.features

const val POWER_PROP = "t_power"
const val BACKLIGHT_PROP = "t_backlight"
const val WORK_MODE_PROP = "t_work_mode"
const val HORIZONTAL_AIR_FLOW_PROP = "t_fan_leftright"
const val VERTICAL_AIR_FLOW_PROP = "t_fan_power"
const val QUIET_PROP = "t_fan_mute"
const val ECO_PROP = "t_eco"
const val BOOST_PROP = "t_temp_heatcold"
const val SLEEP_MODE_PROP = "t_sleep"
const val FAN_SPEED_PROP = "t_fan_speed"
const val ROOM_TEMP_PROP = "f_temp_in"
const val TEMP_PROP = "t_temp"
const val TEMP_TYPE_PROP = "t_temptype"